---
title: "Viktor_Batih's skill showcase"
output: html_notebook
---

```{r}
library(jsonlite)
library(readr)
library(ggplot2)
library(wordcloud)
library(wordcloud2)
library(stringi)
library(psych)
library(RecordLinkage)
library(udpipe)
library(textrank)
library(lattice)
library(igraph)
library(ggraph)
library(dplyr)
library(stringr)
library(tm)
library(rvest)
library(tidyverse)
library(quanteda)
library(lsa)
library(ggdark)
library(pdftools)
library(tibble)
library(ggplot2)
library(grid)
library(viridisLite)
library(tidytext)
library(textclean)
library(textTinyR)
library(gridExtra)
main_data <- read_csv("D:\\papka\\data.csv")
filtered_main_data <- filter(main_data, clean_text > 350)
filtered_main_data$date <- as.POSIXct(filtered_main_data$date, format = "%Y-%m-%dT%H:%M:%S")
result_of_grouping <- filtered_main_data %>%
  mutate(date = as.POSIXct(date, format = "%Y-%m-%dT%H:%M:%S")) %>%
  filter(!is.na(date)) %>%
  mutate(year = format(date, "%Y"),
         month = format(date, "%m")) %>%
  group_by(year, month) %>%
  summarise(count = n())
line_plot <- filter(result_of_grouping, year == 2020)
```
```{r}
a <- ggplot(line_plot, aes(x = month, y = count, group = 1)) +
  geom_line(color = "yellow", linewidth = 1.15) +
  geom_point(data = data.frame(x = c(2, 8, 10), y = c(3, 7, 5)), aes(x = x, y = y), color = "white", size = 2.5) +
  theme(
    panel.background = element_rect(fill = "black"),
    text = element_text(size = 10),
    plot.title = element_text(color = "white", face = "bold", size = 12)
  ) +
  dark_theme_bw() +
  scale_y_continuous(breaks = seq(0, 70, by = 5), limits = c(0, 70)) +
  scale_x_discrete(label = month.abb) +
  labs(title = "Найбільші івенти 2020 року на шкалі публікацій у внутрішньому", x = "Місяць", y = "Кількість") +
  geom_text(x = 10.5, y = 11, label = "Нове \n правління", color = "white") +
  geom_text(x = 2, y = 7, label = "СМК", color = "white") +
  geom_text(x = 7.8, y = 11, label = "ПЛка", color = "white") +
  geom_ribbon(aes(ymax = count, ymin = 0), fill = "yellow", alpha = 0.5)
print(a)
#all other years I did manually
```
```{r}
ukr_model <- udpipe_download_model(language = "ukrainian")
udmodel_ukr <- udpipe_load_model(file = ukr_model)

annotated_text <- udpipe_annotate(udmodel_ukr, x = paste(filtered_main_data$clean_text, collapse = " "))
annotated_text <- as.data.frame(annotated_text)
annotated_text$lemma <- replace(annotated_text$lemma, annotated_text$lemma == "дедлай", "дедлайн")
annotated_text$lemma <- replace(annotated_text$lemma, annotated_text$lemma == "виби", "вибір")
annotated_text$lemma <- replace(annotated_text$lemma, annotated_text$lemma == "усснути", "усс")
annotated_text <- annotated_text[!annotated_text$upos == "X", ]
annotated_text <- annotated_text[!annotated_text$upos == "SYM", ]
annotated_text <- annotated_text[!endsWith(annotated_text$lemma, "."),]
annotated_text <- annotated_text[!endsWith(annotated_text$lemma, "-"),]
annotated_text <- annotated_text[!annotated_text$lemma == "",]
```
```{r}
for_wordcloud <- textrank_keywords(annotated_text$lemma, 
                                   relevant = annotated_text$upos %in% c("NOUN", "ADJ"), ngram_max = 3, sep = " ")
for_wordcloud <- subset(for_wordcloud$keywords, ngram >= 1 & freq >= 30)
pattern_for_duplicates <- "\\b(\\w+)\\b.*\\b\\1\\b"
duplicated_ngrams <- grepl(pattern_for_duplicates, for_wordcloud[,"keyword"])
for_wordcloud <- for_wordcloud[!(duplicated_ngrams == TRUE), ]
wordcloud_data <- data.frame(word = for_wordcloud$keyword, freq = for_wordcloud$freq)
wordcloud2(data = wordcloud_data, color = "yellow", backgroundColor = "dark",
           size = 1.5, minSize = 1, gridSize = 15)
```
```{r}
result_of_grouping <- result_of_grouping[result_of_grouping$year != 2019, ]
plots <- list()
for (year in unique(result_of_grouping$year)) {
  df_subset <- result_of_grouping[result_of_grouping$year == year, ]
  
  plot <- ggplot(df_subset, aes(x = month, y = count, fill = as.factor(year))) +
    geom_bar(stat = "identity", position = position_dodge(width = 0.8), alpha = 1, width = 0.6, fill = "yellow") +
    geom_text(aes(label = count, colour = as.factor(year)), 
              position = position_dodge(width = 0.8), 
              vjust = -0.5, size = 3, color = "white") +
    labs(title = paste("", year),
         x = "Month",
         y = "Count") +
    dark_theme_minimal() +
    theme(legend.position = "none") +
    scale_y_continuous(breaks = seq(0, 100, by = 25), limits = c(0, 100)) +
    scale_x_discrete(labels = month.abb) 
      plots[[as.character(year)]] <- plot
}
grid.arrange(plots[[1]], plots[[2]], plots[[3]], plots[[4]], ncol = 2, nrow = 2)
```
```{r}
create_bar_chart <- function() {
  
  ggplot(result_of_grouping, aes(x = month, y = count, fill = as.factor(year))) +
    geom_bar(stat = "identity", position = "dodge", alpha = 1) +
    geom_text(aes(label = count), position = position_dodge(width = 0.9), 
              vjust = -0.5, hjust = 0.65, size = 3, color = "white") +
    labs(title = "Monthly Publication Count by Year",
         x = "Month",
         y = "Count") +
    dark_theme_minimal() +
    scale_y_continuous(breaks = seq(0, 100, by = 25), limits = c(0, 100)) +
    scale_x_discrete(labels = month.abb) +
    scale_fill_manual(values = c("#C99700", "#F6BE00", "#FBDB65", "yellow"),
                      name = "Year") +
    theme(legend.position = "right")
}

create_bar_chart()
```




